Apache Arrow support
PolusAI/nyxus pull request #122
Opened 2023-06-23 13:53 UTC by JesseMckinzie

- Add support for writing to Apache Arrow IPC and Parquet files from the CLI and Python API
- Add documentation for writing to Arrow
- Add unit tests for writing to Arrow

2023-06-26 15:12 UTC, sameeul commented on CMakeLists.txt
> +			#COMMAND ${Python_EXECUTABLE} -c "import pyarrow as pa; path=pa.get_library_dirs()[0] + '/libarrow_python.dylib'; print(path)"
remove old/stale code

2023-06-26 15:12 UTC, sameeul commented on CMakeLists.txt
> +	#list(APPEND Nyxus_LIBRARIES ${ARROW_LIB})
remove old/stale code

2023-06-26 15:12 UTC, sameeul commented on CMakeLists.txt
> +		find_package(Python REQUIRED COMPONENTS Interpreter Development)
can you check if we can get away w/o using this? Since we already find Python at the beginning.

2023-06-26 15:12 UTC, sameeul commented on CMakeLists.txt
> +		#find_package(arrow_python_shared REQUIRED)
remove old/stale code

2023-06-27 15:36 UTC, friskluft requested changes
I'd require editing Environment::show_cmdline_help() and grouping #define ARROW_OUPUT_TYPE "--arrowOutputType" together with the other CLI options. 
Speaking of functionality, we need to fix the PythonAPI to avoid creation of idle features data frame in Apache scenarios.

2023-06-27 15:36 UTC, friskluft commented on src/nyx/environment.h
> +#define ARROW_OUPUT_TYPE "--arrowOutputType"
This define is declared in a wrong position in the file: it follows feature group nicknames. All the command line options are grouped together in lines 19-60.

2023-06-27 15:36 UTC, friskluft commented on src/nyx/environment.h
> +#define ARROW_OUPUT_TYPE "--arrowOutputType"
What's critical: the help text issued by Environment::show_cmdline_help() doesn't mention the --arrowOutputType options. You need to edit show_cmdline_help()

2023-07-13 14:13 UTC, sameeul commented on ci-utils/install_prereq_linux.sh
> +cd ../../
Can you build and install pyarrow here also like Windows?

2023-07-13 14:21 UTC, sameeul commented on ci-utils/envs/conda_cpp.txt
> +arrow-cpp>=10.0.0
lint :-)

2023-07-21 14:47 UTC, friskluft approved these changes

2023-07-24 13:51 UTC, merged